import {FrontmatterFieldDefinition, FrontmatterFieldGroup, FrontmatterFieldSource} from "./types";

export const FRONTMATTER_GROUP_LABELS: Record<FrontmatterFieldGroup, string> = {
	required: "必填字段",
	recommended: "推荐字段",
	images: "图片字段",
	fixit: "FixIt 功能",
	visibility: "隐藏控制",
	seo: "SEO 与路径",
	advanced: "高级字段",
	external: "外链文章",
	compatibility: "兼容字段",
};

export const FRONTMATTER_SOURCE_LABELS: Record<FrontmatterFieldSource, string> = {
	obsidian: "Obsidian",
	hugo: "Hugo",
	theme: "主题/FixIt",
	custom: "自定义/LCG",
};

// defaultValue is intentionally omitted for all fields — users fill values explicitly.
export const LCG_FRONTMATTER_FIELDS: FrontmatterFieldDefinition[] = [
	{
		key: "title",
		label: "文章标题",
		type: "string",
		group: "required",
		source: "hugo",
		required: true,
		defaultValue: "\"\"",
		description: "文章主标题，会显示在文章页、列表页、搜索结果和浏览器标题中。",
		example: "Hugo 安装与配置",
	},
	{
		key: "date",
		label: "发布时间",
		type: "string",
		group: "required",
		source: "hugo",
		required: true,
		defaultValue: "",
		description: "文章发布时间。Hugo 用它排序、生成归档并显示发布元信息。",
		example: "2026-05-10T00:00:00+08:00",
	},
	{
		key: "draft",
		label: "草稿状态",
		type: "boolean",
		group: "required",
		source: "hugo",
		required: true,
		defaultValue: "true",
		description: "设为 true 时是草稿；正式发布前应改为 false。",
		example: "false",
	},
	{
		key: "description",
		label: "SEO 描述",
		type: "string",
		group: "required",
		source: "hugo",
		required: true,
		defaultValue: "\"\"",
		description: "页面 meta description 和搜索索引摘要。建议写成一句完整说明。",
		example: "Hugo 静态网站生成器的安装与基本配置指南",
	},
	{
		key: "summary",
		label: "列表摘要",
		type: "string",
		group: "required",
		source: "hugo",
		required: true,
		defaultValue: "\"\"",
		description: "首页、分类页和合集页的文章摘要；避免列表页自动截断正文。",
		example: "Hugo 静态网站生成器的安装与基本配置指南",
	},
	{
		key: "categories",
		label: "分类",
		type: "string[]",
		group: "recommended",
		source: "custom",
		required: false,
		defaultValue: "[]",
		description: "文章主分类。你的 LCG 规则建议每篇文章一个主分类。",
		example: "[\"Linux\"]",
	},
	{
		key: "tags",
		label: "标签",
		type: "string[]",
		group: "recommended",
		source: "hugo",
		required: false,
		defaultValue: "[]",
		description: "文章标签，用于标签页、搜索元信息和相关文章发现。",
		example: "[\"hugo\", \"obsidian\"]",
	},
	{
		key: "collections",
		label: "合集",
		type: "string[]",
		group: "recommended",
		source: "theme",
		required: false,
		defaultValue: "[]",
		description: "FixIt 合集归档。适合 NAS、Linux、游历这类连续主题。",
		example: "[\"Linux\"]",
	},
	{
		key: "featuredImage",
		label: "文章头图",
		type: "string",
		group: "images",
		source: "theme",
		required: false,
		defaultValue: "\"\"",
		description: "文章详情页顶部大图。可使用 Obsidian 附件路径或站点可访问 URL。",
		example: "https://cdn.assets.inkyflow.com/content/post/feature.jpg",
	},
	{
		key: "featuredImagePreview",
		label: "首页预览图",
		type: "string",
		group: "images",
		source: "theme",
		required: false,
		defaultValue: "\"\"",
		description: "首页和列表页卡片预览图。为空时 FixIt 会回退到 featuredImage。",
		example: "https://cdn.assets.inkyflow.com/content/post/preview.jpg",
	},
	{
		key: "toc",
		label: "目录",
		type: "boolean",
		group: "fixit",
		source: "theme",
		required: false,
		defaultValue: "true",
		description: "控制 FixIt 文章目录。可用 true/false，或后续扩展成对象配置。",
		example: "true",
	},
	{
		key: "math",
		label: "数学公式",
		type: "boolean",
		group: "fixit",
		source: "theme",
		required: false,
		defaultValue: "false",
		description: "启用 KaTeX 数学公式渲染。只有文章包含公式时才建议开启。",
		example: "false",
	},
	{
		key: "lightgallery",
		label: "图片画廊",
		type: "boolean",
		group: "fixit",
		source: "theme",
		required: false,
		defaultValue: "true",
		description: "启用 FixIt 图片灯箱浏览。图片较多的游记和教程建议开启。",
		example: "true",
	},
	{
		key: "comment",
		label: "评论",
		type: "boolean",
		group: "fixit",
		source: "theme",
		required: false,
		defaultValue: "false",
		description: "覆盖站点默认评论设置。true 使用站点评论配置，false 关闭当前页评论。",
		example: "false",
		advanced: true,
	},
	{
		key: "hiddenFromHomePage",
		label: "隐藏于首页",
		type: "boolean",
		group: "visibility",
		source: "theme",
		required: false,
		defaultValue: "false",
		description: "设为 true 后文章不出现在首页列表，适合关于页或特殊页面。",
		example: "true",
	},
	{
		key: "hiddenFromSearch",
		label: "隐藏于搜索",
		type: "boolean",
		group: "visibility",
		source: "theme",
		required: false,
		defaultValue: "false",
		description: "设为 true 后不进入站内搜索索引。",
		example: "true",
	},
	{
		key: "hiddenFromFeed",
		label: "隐藏于订阅",
		type: "boolean",
		group: "visibility",
		source: "theme",
		required: false,
		defaultValue: "false",
		description: "设为 true 后不显示在 RSS、Atom 和 JSON Feed 中。",
		example: "true",
	},
	{
		key: "hiddenFromRelated",
		label: "隐藏于相关文章",
		type: "boolean",
		group: "visibility",
		source: "theme",
		required: false,
		defaultValue: "false",
		description: "设为 true 后不会作为相关文章被推荐。",
		example: "true",
	},
	{
		key: "slug",
		label: "短链接名",
		type: "string",
		group: "seo",
		source: "hugo",
		required: false,
		defaultValue: "\"\"",
		description: "自定义文章 URL slug。发布后不要轻易修改，否则会改变链接。",
		example: "ugreen-nas-kernel-tuning",
	},
	{
		key: "url",
		label: "固定 URL",
		type: "string",
		group: "seo",
		source: "hugo",
		required: false,
		defaultValue: "\"\"",
		description: "完全指定页面路径。只建议关于页、隐私页等固定页面使用。",
		example: "/about/",
		advanced: true,
	},
	{
		key: "keywords",
		label: "关键词",
		type: "string[]",
		group: "seo",
		source: "theme",
		required: false,
		defaultValue: "[]",
		description: "SEO 关键词。多数文章用 tags 即可，只有需要额外关键词时填写。",
		example: "[\"Hugo\", \"FixIt\", \"Obsidian\"]",
		advanced: true,
	},
	{
		key: "lastmod",
		label: "最后修改时间",
		type: "string",
		group: "seo",
		source: "hugo",
		required: false,
		defaultValue: "",
		description: "最后更新时间。FixIt 可在开启 showLastmod 时显示更新日期。",
		example: "2026-05-10T00:00:00+08:00",
	},
	{
		key: "subtitle",
		label: "副标题",
		type: "string",
		group: "advanced",
		source: "theme",
		required: false,
		defaultValue: "\"\"",
		description: "文章页标题下方的补充文案。适合需要解释标题语境的文章。",
		example: "极限性能与稳定性的平衡艺术",
	},
	{
		key: "author",
		label: "作者",
		type: "object",
		group: "advanced",
		source: "theme",
		required: false,
		defaultValue: "\n  name: \"\"\n  link: \"\"\n  email: \"\"\n  avatar: \"\"",
		description: "覆盖站点默认作者信息。个人博客通常不需要每篇文章单独设置。",
		advanced: true,
	},
	{
		key: "weight",
		label: "权重",
		type: "number",
		group: "advanced",
		source: "theme",
		required: false,
		defaultValue: "0",
		description: "用于排序或置顶提示。FixIt 摘要列表会对非零权重显示置顶图标。",
		example: "1",
		advanced: true,
	},
	{
		key: "password",
		label: "文章密码",
		type: "string",
		group: "advanced",
		source: "theme",
		required: false,
		defaultValue: "\"\"",
		description: "启用 FixIt 内容加密。公开博客慎用，搜索和阅读体验会受影响。",
		advanced: true,
	},
	{
		key: "message",
		label: "密码提示",
		type: "string",
		group: "advanced",
		source: "theme",
		required: false,
		defaultValue: "\"\"",
		description: "加密文章的密码输入提示文案。",
		advanced: true,
	},
	{
		key: "repost",
		label: "转载标记",
		type: "object",
		group: "advanced",
		source: "theme",
		required: false,
		defaultValue: "\n  enable: false\n  url: \"\"",
		description: "标记为转载或外部来源文章，并可显示原文链接。",
		advanced: true,
	},
	{
		key: "externalUrl",
		label: "外链地址",
		type: "string",
		group: "external",
		source: "theme",
		required: false,
		defaultValue: "\"\"",
		description: "外链文章跳转目标。适合只在站点列表保留一个外部文章入口。",
		example: "https://example.com/post",
	},
	{
		key: "_build",
		label: "构建行为",
		type: "object",
		group: "external",
		source: "hugo",
		required: false,
		defaultValue: "\n  render: false\n  list: local",
		description: "控制 Hugo 是否渲染页面、是否进入列表。外链文章通常 render 为 false。",
		advanced: true,
	},
	{
		key: "showTableOfContents",
		label: "旧目录开关",
		type: "boolean",
		group: "compatibility",
		source: "theme",
		required: false,
		defaultValue: "true",
		description: "旧主题/旧习惯字段。FixIt 推荐使用 toc。",
		deprecated: true,
	},
	{
		key: "showReadingTime",
		label: "旧阅读时间开关",
		type: "boolean",
		group: "compatibility",
		source: "theme",
		required: false,
		defaultValue: "true",
		description: "旧主题/旧习惯字段。FixIt 推荐使用 readingTime 或站点默认配置。",
		deprecated: true,
	},
	{
		key: "showWordCount",
		label: "旧字数开关",
		type: "boolean",
		group: "compatibility",
		source: "theme",
		required: false,
		defaultValue: "true",
		description: "旧主题/旧习惯字段。FixIt 推荐使用 wordCount 或站点默认配置。",
		deprecated: true,
	},
];

export const DEFAULT_TEMPLATE_FIELD_KEYS = [
	"title",
	"date",
	"draft",
	"description",
	"summary",
	"categories",
	"tags",
	"collections",
	"toc",
	"math",
	"lightgallery",
] as const;

export const REQUIRED_FIELD_KEYS = LCG_FRONTMATTER_FIELDS
	.filter((field) => field.required)
	.map((field) => field.key);

export const ARRAY_FIELD_KEYS = LCG_FRONTMATTER_FIELDS
	.filter((field) => field.type === "string[]")
	.map((field) => field.key);

export const COMPATIBILITY_FIELD_KEYS = LCG_FRONTMATTER_FIELDS
	.filter((field) => field.deprecated)
	.map((field) => field.key);

export function getFieldDefinition(key: string): FrontmatterFieldDefinition | undefined {
	return LCG_FRONTMATTER_FIELDS.find((field) => field.key === key);
}
