import {FrontmatterFieldDefinition, FrontmatterFieldGroup, FrontmatterFieldSource} from "./types";
import {t} from "../i18n";
import type {Translations} from "../i18n/types";

type TranslationKey = keyof Translations;

export const FRONTMATTER_GROUP_LABELS: Record<FrontmatterFieldGroup, string> = {
	required: "Required",
	recommended: "Recommended",
	images: "Images",
	fixit: "FixIt",
	visibility: "Visibility",
	seo: "SEO",
	advanced: "Advanced",
	external: "External",
	compatibility: "Compatibility",
	other: "Other",
};

export const FRONTMATTER_SOURCE_LABELS: Record<FrontmatterFieldSource, string> = {
	obsidian: "Obsidian",
	hugo: "Hugo",
	theme: "Theme",
	custom: "Custom",
};

export function getFieldLabel(field: FrontmatterFieldDefinition): string {
	const key = `field.label.${field.key}` as TranslationKey;
	return t(key);
}

export function getFieldDescription(field: FrontmatterFieldDefinition): string {
	const key = `field.desc.${field.key}` as TranslationKey;
	return t(key);
}

export function getGroupLabel(group: FrontmatterFieldGroup): string {
	const key = `field.group.${group}` as TranslationKey;
	return t(key);
}

export function getSourceLabel(source: FrontmatterFieldSource): string {
	const key = `field.source.${source}` as TranslationKey;
	return t(key);
}

export const LCG_FRONTMATTER_FIELDS: FrontmatterFieldDefinition[] = [
	{
		key: "title",
		label: "Title",
		type: "string",
		group: "required",
		source: "hugo",
		required: true,
		defaultValue: "\"\"",
		description: "The title of the article.",
		example: "Getting Started with Hugo",
	},
	{
		key: "date",
		label: "Publish Date",
		type: "string",
		group: "required",
		source: "hugo",
		required: true,
		defaultValue: "",
		description: "The date the article was published.",
		example: "2026-05-10T00:00:00+08:00",
	},
	{
		key: "draft",
		label: "Draft",
		type: "boolean",
		group: "required",
		source: "hugo",
		required: true,
		defaultValue: "true",
		description: "Set to true for draft; change to false before publishing.",
		example: "false",
	},
	{
		key: "description",
		label: "Description",
		type: "string",
		group: "required",
		source: "hugo",
		required: true,
		defaultValue: "\"\"",
		description: "Meta description for SEO and search results.",
		example: "A guide to getting started with Hugo",
	},
	{
		key: "summary",
		label: "Summary",
		type: "string",
		group: "required",
		source: "hugo",
		required: true,
		defaultValue: "\"\"",
		description: "Custom summary for the article.",
		example: "Learn how to use Hugo with Obsidian",
	},
	{
		key: "categories",
		label: "Categories",
		type: "string[]",
		group: "recommended",
		source: "custom",
		required: false,
		defaultValue: "[]",
		description: "Article categories.",
		example: "[\"Linux\"]",
	},
	{
		key: "tags",
		label: "Tags",
		type: "string[]",
		group: "recommended",
		source: "hugo",
		required: false,
		defaultValue: "[]",
		description: "Article tags.",
		example: "[\"hugo\", \"obsidian\"]",
	},
	{
		key: "series",
		label: "Series",
		type: "string[]",
		group: "recommended",
		source: "custom",
		required: false,
		defaultValue: "[]",
		description: "Article series.",
		example: "[\"Linux\"]",
	},
	{
		key: "collections",
		label: "Collections",
		type: "string[]",
		group: "recommended",
		source: "theme",
		required: false,
		defaultValue: "[]",
		description: "Article collections.",
		example: "[\"Linux\"]",
	},
	{
		key: "featuredImage",
		label: "Featured Image",
		type: "string",
		group: "images",
		source: "theme",
		required: false,
		defaultValue: "\"\"",
		description: "Featured image URL.",
		example: "https://cdn.example.com/feature.jpg",
	},
	{
		key: "featuredImagePreview",
		label: "Preview Image",
		type: "string",
		group: "images",
		source: "theme",
		required: false,
		defaultValue: "\"\"",
		description: "Preview image for cards and lists.",
		example: "https://cdn.example.com/preview.jpg",
	},
	{
		key: "toc",
		label: "Table of Contents",
		type: "boolean",
		group: "fixit",
		source: "theme",
		required: false,
		defaultValue: "true",
		description: "Enable table of contents.",
		example: "true",
	},
	{
		key: "math",
		label: "Math",
		type: "boolean",
		group: "fixit",
		source: "theme",
		required: false,
		defaultValue: "false",
		description: "Enable KaTeX math rendering.",
		example: "false",
	},
	{
		key: "lightgallery",
		label: "Gallery",
		type: "boolean",
		group: "fixit",
		source: "theme",
		required: false,
		defaultValue: "true",
		description: "Enable image gallery lightbox.",
		example: "true",
	},
	{
		key: "comment",
		label: "Comment",
		type: "boolean",
		group: "fixit",
		source: "theme",
		required: false,
		defaultValue: "false",
		description: "Enable comments for this article.",
		example: "false",
		advanced: true,
	},
	{
		key: "hiddenFromHomePage",
		label: "Hidden from Home",
		type: "boolean",
		group: "visibility",
		source: "theme",
		required: false,
		defaultValue: "false",
		description: "Hide from home page.",
		example: "true",
	},
	{
		key: "hiddenFromSearch",
		label: "Hidden from Search",
		type: "boolean",
		group: "visibility",
		source: "theme",
		required: false,
		defaultValue: "false",
		description: "Hide from search index.",
		example: "true",
	},
	{
		key: "hiddenFromFeed",
		label: "Hidden from RSS",
		type: "boolean",
		group: "visibility",
		source: "theme",
		required: false,
		defaultValue: "false",
		description: "Hide from RSS feeds.",
		example: "true",
	},
	{
		key: "hiddenFromRelated",
		label: "Hidden from Related",
		type: "boolean",
		group: "visibility",
		source: "theme",
		required: false,
		defaultValue: "false",
		description: "Exclude from related posts.",
		example: "true",
	},
	{
		key: "slug",
		label: "Slug",
		type: "string",
		group: "seo",
		source: "hugo",
		required: false,
		defaultValue: "\"\"",
		description: "Custom URL slug.",
		example: "my-article-slug",
	},
	{
		key: "url",
		label: "URL",
		type: "string",
		group: "seo",
		source: "hugo",
		required: false,
		defaultValue: "\"\"",
		description: "Full custom URL.",
		example: "/about/",
		advanced: true,
	},
	{
		key: "keywords",
		label: "Keywords",
		type: "string[]",
		group: "seo",
		source: "theme",
		required: false,
		defaultValue: "[]",
		description: "SEO keywords.",
		example: "[\"Hugo\", \"FixIt\", \"Obsidian\"]",
		advanced: true,
	},
	{
		key: "lastmod",
		label: "Last Modified",
		type: "string",
		group: "seo",
		source: "hugo",
		required: false,
		defaultValue: "",
		description: "Last modified date.",
		example: "2026-05-10T00:00:00+08:00",
	},
	{
		key: "subtitle",
		label: "Subtitle",
		type: "string",
		group: "advanced",
		source: "theme",
		required: false,
		defaultValue: "\"\"",
		description: "Article subtitle.",
		example: "A comprehensive guide",
	},
	{
		key: "author",
		label: "Author",
		type: "object",
		group: "advanced",
		source: "theme",
		required: false,
		defaultValue: "\n  name: \"\"\n  link: \"\"\n  email: \"\"\n  avatar: \"\"",
		description: "Article author.",
		advanced: true,
	},
	{
		key: "weight",
		label: "Weight",
		type: "number",
		group: "advanced",
		source: "theme",
		required: false,
		defaultValue: "0",
		description: "Sort weight for ordering.",
		example: "1",
		advanced: true,
	},
	{
		key: "password",
		label: "Password",
		type: "string",
		group: "advanced",
		source: "theme",
		required: false,
		defaultValue: "\"\"",
		description: "Content password protection.",
		advanced: true,
	},
	{
		key: "message",
		label: "Password Hint",
		type: "string",
		group: "advanced",
		source: "theme",
		required: false,
		defaultValue: "\"\"",
		description: "Password hint text.",
		advanced: true,
	},
	{
		key: "repost",
		label: "Repost",
		type: "object",
		group: "advanced",
		source: "theme",
		required: false,
		defaultValue: "\n  enable: false\n  url: \"\"",
		description: "Mark as reposted article.",
		advanced: true,
	},
	{
		key: "externalUrl",
		label: "External URL",
		type: "string",
		group: "external",
		source: "theme",
		required: false,
		defaultValue: "\"\"",
		description: "External article URL.",
		example: "https://example.com/post",
	},
	{
		key: "_build",
		label: "Build",
		type: "object",
		group: "external",
		source: "hugo",
		required: false,
		defaultValue: "\n  render: false\n  list: local",
		description: "Build configuration for Hugo.",
		advanced: true,
	},
	{
		key: "showTableOfContents",
		label: "Old TOC",
		type: "boolean",
		group: "compatibility",
		source: "theme",
		required: false,
		defaultValue: "true",
		description: "Legacy TOC field (use 'toc' instead).",
		deprecated: true,
	},
	{
		key: "showReadingTime",
		label: "Old Reading Time",
		type: "boolean",
		group: "compatibility",
		source: "theme",
		required: false,
		defaultValue: "true",
		description: "Legacy field (use 'readingTime' instead).",
		deprecated: true,
	},
	{
		key: "showWordCount",
		label: "Old Word Count",
		type: "boolean",
		group: "compatibility",
		source: "theme",
		required: false,
		defaultValue: "true",
		description: "Legacy field (use 'wordCount' instead).",
		deprecated: true,
	},
];

export const DEFAULT_TEMPLATE_FIELD_KEYS = [
	"title",
	"date",
	"draft",
	"description",
	"summary",
	"categories",
	"tags",
	"collections",
	"toc",
	"math",
	"lightgallery",
] as const;

export const REQUIRED_FIELD_KEYS = LCG_FRONTMATTER_FIELDS
	.filter((field) => field.required)
	.map((field) => field.key);

export const ARRAY_FIELD_KEYS = LCG_FRONTMATTER_FIELDS
	.filter((field) => field.type === "string[]")
	.map((field) => field.key);

export const COMPATIBILITY_FIELD_KEYS = LCG_FRONTMATTER_FIELDS
	.filter((field) => field.deprecated)
	.map((field) => field.key);

export function getFieldDefinition(key: string): FrontmatterFieldDefinition | undefined {
	return LCG_FRONTMATTER_FIELDS.find((field) => field.key === key);
}
